#!/bin/sh
#
# xenmagic:	Start/stop xenmagic service
#
# chkconfig:	2345 25 90
# description: XenMagic is a web-based open source clone of Xencenter.	
#


# Source function library.
. /etc/rc.d/init.d/functions

start()
{
	echo -n $"Starting XenMagic service:"
	daemon --user=xenwm  /usr/bin/xenmagic -daemon 
	touch /var/lock/subsys/xenmagic
	echo ""
}

stop()
{
	echo -n "Stopping XenMagic service:"
	killproc xenmagic 
	rm -f /var/lock/subsys/xenmagic
	echo ""
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
        stop
        start
        ;;
  condrestart)
        [ -e /var/lock/subsys/xenmagic ] && (stop; start)
        ;;
  status)
        status xenmagic
        ;;
  *)
        echo $"Usage: $0 {start|stop|status|restart|reload|condrestart}"
        exit 1
	;;
esac

exit 0
